version: '3.8'

services:

  db:
    image: mysql:9.0.1
    container_name: mysql
    ports:
      - "30306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: west60load
      MYSQL_DATABASE: drive_db
      MYSQL_USER: developer
      MYSQL_PASSWORD: jhg32ifiod2
    networks:
      - backend

  redis:
    image: redis:7.4.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: file-drive
    depends_on:
      redis:
          condition: service_healthy
      db:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/drive_db
      SPRING_DATASOURCE_USERNAME: developer
      SPRING_DATASOURCE_PASSWORD: jhg32ifiod2
      SPRING_REDIS_URL: redis://172.18.0.1:6379
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge