version: '3.8'

services:

  db:
    image: mysql:9.0.1
    container_name: mysql
    ports:
      - "30306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: west60load
      MYSQL_DATABASE: drive_db
      MYSQL_USER: developer
      MYSQL_PASSWORD: jhg32ifiod2
    networks:
      - webapp

  redis:
    image: redis:7.4.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - webapp
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z
    container_name: minio
    ports:
      - '9002:9000'
      - '9000:9001'
    restart: always
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: mg3hg3i8qc
    command: server /data
    volumes:
      - minio-storage:/data
    networks:
      - webapp

  app:
    container_name: file-drive
    build:
      dockerfile: Dockerfile
    depends_on:
      redis:
          condition: service_healthy
      db:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/drive_db
      SPRING_DATASOURCE_USERNAME: developer
      SPRING_DATASOURCE_PASSWORD: jhg32ifiod2
      SPRING_DATA_REDIS_URL: redis://172.18.0.1:6379
    ports:
      - "8080:8080"
    networks:
      - webapp

networks:
  webapp:
    driver: bridge

volumes:
  minio-storage:
    driver: local